# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  push:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    # Run docker compose
    - name: Docker Compose Action
      uses: hoverkraft-tech/compose-action@v2.0.2
      with:
        # Description: Path to compose file(s). It can be a list of files. It can be
        # absolute or relative to the current working directory (cwd).
        #
        # Default: ./docker-compose.yml
        compose-file: "./docker-compose.yaml"
